config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
    namespace :api do
      resources :wishlists, only: [:create, :destroy]
  end
  resources :properties, only: [:show]
end

app/models/amenity.rb
class Amenity < ApplicationRecord
	validates :name, presence: true

  has_one_attached :icon

  has_many :property_amenities, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  validates :name, presence: :true
  validates :headline, presence: :true
  validates :description, presence: :true
  validates :address_1, presence: :true
  validates :city, presence: :true
  validates :state, presence: :true
  validates :country, presence: :true
  
  monetize :price_cents, allow_nil: true
  
  has_many_attached :images

  has_many :reviews, dependent: :destroy 

  has_many :property_amenities, dependent: :destroy
  has_many :amenities, through: :property_amenities, source: :amenity, dependent: :destroy

  has_many :wishlists, dependent: :destroy

  has_many :wishlists_users, through: :wishlists, source: :user,  dependent: :destroy

  
  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user, dependent: :destroy
  
  has_rich_text :description
  def update_average_rating
    average_rating = reviews.average(:final_rating)
    update_column(:average_final_rating, average_rating)
  end

  def average_cleanliness_rating
    reviews.average(:cleanliness_rating)
  end

  def average_accuracy_rating
    reviews.average(:accuracy_rating)
  end

  def average_checking_rating
    reviews.average(:checking_rating)
  end

  def average_communication_rating
    reviews.average(:communication_rating)
  end

  def average_location_rating
    reviews.average(:location_rating)
  end

  def average_value_rating
    reviews.average(:value_rating)
  end

  def wishlisted_by?(user = nil)
    return if user.nil?

    wishlists_users.include?(user)
  end


   def available_dates
    next_reservation = reservations.upcoming_reservations.first
    current_reservation = reservations.current_reservations.first

    if current_reservation.nil? && next_reservation.nil?
      Date.tomorrow.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')
    elsif current_reservation.nil?
      Date.tomorrow.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')
    elsif next_reservation.nil?
      current_reservation.checkout_date.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')
    else
      current_reservation.checkout_date.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')
    end
  end
end

app/models/property_amenity.rb
class PropertyAmenity < ApplicationRecord
  belongs_to :property
  belongs_to :amenity
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :checkin_date, presence: true
  validates :checkout_date, presence: true

  scope :upcoming_reservations, -> { where("checkin_date > ?", Date.today).order(:checkin_date) }
  scope :current_reservations, -> { where("checkout_date > ?", Date.today).where("checkin_date < ?", Date.today).order(:checkout_date) }


  scope :overlapping_reservations, -> (checkin_date, checkout_date) {
    where(
      '(checkin_date < ? AND checkout_date > ?) OR
      (checkin_date < ? AND checkout_date > ?) OR
      (checkin_date > ? AND checkout_date < ?) OR
      (checkin_date < ? AND checkout_date > ?)',
      checkin_date, checkin_date,
      checkout_date, checkout_date,
      checkin_date, checkout_date,
      checkin_date, checkout_date
    )
  }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :property, counter_cache:true

  validates :content, presence: true
  validates :cleanliness_rating, numericality: {only_integer: true,  greater_than_or_equal_to: 1, less_than_equal_to: 5}
  validates :accuracy_rating, numericality: {only_integer: true,  greater_than_or_equal_to: 1, less_than_equal_to: 5}
  validates :checking_rating, numericality: {only_integer: true,  greater_than_or_equal_to: 1, less_than_equal_to: 5}
  validates :communication_rating, numericality: {only_integer: true,  greater_than_or_equal_to: 1, less_than_equal_to: 5}
  validates :location_rating, numericality: {only_integer: true,  greater_than_or_equal_to: 1, less_than_equal_to: 5}
  validates :value_rating, numericality: {only_integer: true,  greater_than_or_equal_to: 1, less_than_equal_to: 5}

  after_commit :update_final_rating, om: [:create, :update]

  def update_final_rating
    total_points = cleanliness_rating + 
    accuracy_rating + 
    checking_rating + 
    communication_rating + 
    location_rating +
    value_rating
    
    update_column(:final_rating, total_points.to_f / 6)

    property.update_average_rating
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, presence:true
  validates :address_1, presence:true
  validates :city, presence: true
  validates :state, presence:true
  validates :country, presence:true 


  has_one_attached :picture        

  has_many :wishlists, dependent: :destroy

  has_many :wishlists_properties, through: :wishlists, source: :property,  dependent: :destroy
  

  has_many :reservations, dependent: :destroy
  has_many :reserved_properties, through: :reservations, source: :property, dependent: :destroy
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/controllers/api/wishlists_controller.rb
module Api
  class WishlistsController < ApplicationController
    protect_from_forgery with: :null_session

    def create
      wishlist = Wishlist.create!(wishlist_params)

      respond_to do |format|
        format.json do
          render json: wishlist.to_json, status: :ok
        end
      end
    end

    def destroy
      wishlist = Wishlist.find(params[:id])
      wishlist.destroy

      respond_to do |format|
        format.json do
          render json: wishlist.to_json, status: 204
        end
      end
    end

    private

    def wishlist_params
      params.permit(:user_id, :property_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.all
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	def show
	 @property = Property.includes(:reviews).find(params[:id])
	    @overall_rating_counts = @property
	                              .reviews
	                              .group('ROUND(final_rating)')
	                              .count
	                              .transform_keys(&:to_i)
	    
	    @overall_rating_counts.default = 0
	  end
	end

app/helpers/api/wishlists_helper.rb
module Api::WishlistsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
      	<% @properties.each do |property| %>
        <%= link_to property_path(property) do%>
      <div class="group relative cursor-pointer">
    <div class="relative overflow-hidden rounded-md bg-gray-200">
      <div class="swiper">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
          <% property.images.each do |image| %>
            <%= image_tag image, class:"swiper-slide h-full w-full object-cover object-center lg:h-full lg:w-full" %>
          <% end %>
        </div>
        
        <%# TODO: Swiper buttons are not working %>
        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
      </div>

      <div class="absolute z-10 right-0 top-0 m-4">
        <svg xmlns="http://www.w3.org/2000/svg" 
          viewBox="0 0 32 32" 
          aria-hidden="true" 
          role="presentation" 
          focusable="false"
          class="block h-6 w-6 stroke-white stroke-2 <%= property.wishlisted_by?(current_user) ? 'fill-primary' : 'fill-none' %>"
          style="overflow: visible;"
          data-controller="wishlist"
          data-user-logged-in="<%= user_signed_in? %>"
          data-property-id="<%= property.id %>"
          data-user-id="<%= current_user&.id %>"
          data-wishlist-id="<%= property.wishlists.find_by(user: current_user)&.id %>"
          data-action="click->wishlist#updateWishlistStatus"
          data-wishlist-target="icon"
          data-status="<%= property.wishlisted_by?(current_user) %>"
          >
            <path d="M16 28c7-4.73 14-10 14-17a6.98 6.98 0 0 0-7-7c-1.8 0-3.58.68-4.95 2.05L16 8.1l-2.05-2.05a6.98 6.98 0 0 0-9.9 0A6.98 6.98 0 0 0 2 11c0 7 7 12.27 14 17z"></path>
        </svg>
      </div>
    </div>
        <div class="mt-2">
          <div class="flex justify-between">
            <h3 class="text-sm font-medium text-gray-700">
                <%= property.city%>, <%= property.country%>              
            </h3>
            <p class="flex-item-center text-sm font-light fill-current">
            <svg class= "mr-1 block w-3 h-3" 
            xmlns="http://www.w3.org/2000/svg" 
            fill="none" viewBox="0 0 24 24" 
            stroke-width="1.5" 
            stroke="currentColor" 
            class="w-6 h-6"><path 
            stroke-linecap="round" 
            stroke-linejoin="round" 
            d="M11.48 3.499a.562.562 0 0 1 1.04 0l2.125 5.111a.563.563 0 0 0 .475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 0 0-.182.557l1.285 5.385a.562.562 0 0 1-.84.61l-4.725-2.885a.562.562 0 0 0-.586 0L6.982 20.54a.562.562 0 0 1-.84-.61l1.285-5.386a.562.562 0 0 0-.182-.557l-4.204-3.602a.562.562 0 0 1 .321-.988l5.518-.442a.563.563 0 0 0 .475-.345L11.48 3.5Z" />
           </svg>				
            <%= (property.average_final_rating).round(2) %>	
            </p>
          	</div>
            <%# <%= TODO:Add distance from properly based on location %>
            <p class="mt-1 text-sm text-gray-500"><%= property.available_dates.first %> - <%= property.available_dates.last%></p>
            <p class="mt-1 text-sm font-light text-black"><span class="font-medium"><%=humanized_money_with_symbol(property.price)%></span> Night</p>


          </div>
        </div>
        <% end %>
      <%end%>

      <!-- More products... -->
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb | Holiday rentals, cabins, beach houses and more</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <% if controller_name == 'booking_payments' && action_name == 'create'%>
      <%= stripe_javascript_tag %>
    <% end %>

    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

    <%# Date picker: https://flatpickr.js.org/getting-started/ %>
    <%# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"> %>
  </head>

  <body>

    <% if controller_name != 'registrations' && controller_name != 'sessions' %>
      <%= render 'layouts/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/properties/_review_item.html.erb
<div class="flex flex-col py-4">
  <div class="flex items-center">
    <%# if review.user.profile.picture.present? %>
      <%#= image_tag review.user.profile.picture, alt: review.user.profile.name, class:"h-12 w-12 rounded-full" %>
    <%# else %>
      <svg 
        xmlns="http://www.w3.org/2000/svg" 
        fill="none" 
        viewBox="0 0 24 24" 
        stroke-width="1.5" 
        stroke="currentColor" 
        class="h-12 w-12 rounded-full"
      >
        <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
      </svg>
    <%# end %>
      
    <div>
      <p class="text-base text-gray-900 ms-4"><%#= review.user.profile.name %></p>
      <p class="text-xs text-gray-900 ms-4"><%#= review.user.profile.city %>, <%#= country_name(review.user.profile.country_code) %></p>
    </div>
  </div>
  <div class="mt-2 flex items-center">
    <% 5.times do |i| %>
      <svg class="<%= review.final_rating.round(0) > (i) ? 'text-black' : 'text-gray-300'%> h-3 w-3 flex-shrink-0" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
      </svg>
    <% end %>
  </div>
  <div class="mt-6 sm:mt-0">
    <p class="sr-only">5 out of 5 stars</p>

    <div class="mt-3 space-y-6 text-base text-gray-600">
      <p><%= review.content %></p>
    </div>
  </div>
</div>

app/views/properties/_reviews.html.erb
<div class="mx-auto max-w-2xl px-4 pt-8 sm:px-6 lg:max-w-7xl lg:px-8"> 
  <h2 id="reviews-heading" class="sr-only">Reviews</h2>
  <!-- Review Stats -->
  <section aria-labelledby="reviews-stats" class="border-t border-gray-200 pt-10 pb-10">
    <% if property.reviews_count == 0 %>
      <span class="text-2xl font-medium leading-6 text-gray-900 flex items-center">
        <svg 
          xmlns="http://www.w3.org/2000/svg" 
          viewBox="0 0 32 32" 
          aria-hidden="true" 
          role="presentation" 
          focusable="false" 
          class="inline h-6 w-6 fill-current me-2"
        >
            <path d="m10.66 9.74-8.23 1-.15.02a2 2 0 0 0-.93 3.47l6.2 5.46-2 8.52-.03.15a2 2 0 0 0 2.96 2.05L16 26.15l7.52 4.26.13.07a2 2 0 0 0 2.8-2.27l-2-8.52 6.2-5.46.11-.11a2 2 0 0 0-1.19-3.38l-8.23-1-3.53-7.55a2 2 0 0 0-3.62 0zM12 11.59l4-8.56 4 8.56 9.33 1.13-7.1 6.26 2.27 9.69-8.5-4.82-8.5 4.82 2.28-9.7-7.11-6.25z"></path>
        </svg>
        No reviews (yet)
      </span>
    <% else %>
      <div class="mt-1 text-2xl font-medium leading-6 text-gray-900 flex items-center">
        <svg 
          xmlns="http://www.w3.org/2000/svg" 
          viewBox="0 0 32 32" 
          aria-hidden="true" 
          role="presentation" 
          focusable="false"
          class="inline h-5 w-5 fill-current me-2"
        >
          <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
        </svg>
        <span><%= (property.average_final_rating).round(2) %> · <%= property.reviews_count %> reviews</span>
      </div>

      <!-- Review category stats -->
      <div class="grid-cols-7 gap-4 mt-8 divide-x hidden lg:grid">
        <div class="pr-2">
          <h4 class="text-sm font-medium">Overall rating</h4>
          <div class="mt-2">
            <h3 class="sr-only">Review data</h3>

            <dl class="space-y-0">
              <% 5.times do |index| %>
                <div class="flex items-center text-xs">
                  <dt class="flex flex-1 items-center">
                    <p class="w-3 font-medium text-gray-900"><%= (5-index) %><span class="sr-only"> star reviews</span></p>
                    <div aria-hidden="true" class="ml-1 flex flex-1 items-center">
                      <div class="relative ml-1 flex-1">
                        <div class="h-1 rounded-full border border-gray-200 bg-gray-200"></div>
                        <div style="width: <%= (@overall_rating_counts[(5-index)]) * 100 / property.reviews_count %>%" class="absolute inset-y-0 rounded-full border border-black bg-black"></div>
                      </div>
                    </div>
                  </dt>
                </div>
              <% end %>
            </dl>
          </div>
          
        </div>

        <div class="ps-2 sm:ps-4 lg:ps-6">
          <h4 class="text-sm font-medium">Cleanliness</h4>
          <p class="text-lg font-medium"><%= property.average_cleanliness_rating().round(1) %></p>
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false"
            class="block h-8 w-8 fill-current mt-6"
          >
            <path d="M24 0v6h-4.3c.13 1.4.67 2.72 1.52 3.78l.2.22-1.5 1.33a9.05 9.05 0 0 1-2.2-5.08c-.83.38-1.32 1.14-1.38 2.2v4.46l4.14 4.02a5 5 0 0 1 1.5 3.09l.01.25.01.25v8.63a3 3 0 0 1-2.64 2.98l-.18.01-.21.01-12-.13A3 3 0 0 1 4 29.2L4 29.02v-8.3a5 5 0 0 1 1.38-3.45l.19-.18L10 12.9V8.85l-4.01-3.4.02-.7A5 5 0 0 1 10.78 0H11zm-5.03 25.69a8.98 8.98 0 0 1-6.13-2.41l-.23-.23A6.97 6.97 0 0 0 6 21.2v7.82c0 .51.38.93.87 1H7l11.96.13h.13a1 1 0 0 0 .91-.88l.01-.12v-3.52c-.34.04-.69.06-1.03.06zM17.67 2H11a3 3 0 0 0-2.92 2.3l-.04.18-.01.08 3.67 3.1h2.72l.02-.1a4.29 4.29 0 0 1 3.23-3.4zM30 4a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm-3-2a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm-5 0h-2.33v2H22zm8-2a1 1 0 1 1 0 2 1 1 0 0 1 0-2zM20 20.52a3 3 0 0 0-.77-2l-.14-.15-4.76-4.61v-4.1H12v4.1l-5.06 4.78a3 3 0 0 0-.45.53 9.03 9.03 0 0 1 7.3 2.34l.23.23A6.98 6.98 0 0 0 20 23.6z"></path>
          </svg>
        </div>

        <div class="ps-2 sm:ps-4 lg:ps-6 ">
          <h4 class="text-sm font-medium">Accuracy</h4>
          <p class="text-lg font-medium"><%= property.average_accuracy_rating().round(1) %></p>
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false"
            class="block h-8 w-8 fill-current mt-6"
          >
            <path d="M16 1a15 15 0 1 1 0 30 15 15 0 0 1 0-30zm0 2a13 13 0 1 0 0 26 13 13 0 0 0 0-26zm7 7.59L24.41 12 13.5 22.91 7.59 17 9 15.59l4.5 4.5z"></path>
          </svg>
        </div>

        <div class="ps-2 sm:ps-4 lg:ps-6 ">
          <h4 class="text-sm font-medium">Check-in</h4>
          <p class="text-lg font-medium"><%= property.average_checking_rating().round(1) %></p>
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false"
            class="block h-8 w-8 fill-current mt-6"
          >
            <path d="M16.84 27.16v-3.4l-.26.09c-.98.32-2.03.51-3.11.55h-.7A11.34 11.34 0 0 1 1.72 13.36v-.59A11.34 11.34 0 0 1 12.77 1.72h.59c6.03.16 10.89 5.02 11.04 11.05V13.45a11.3 11.3 0 0 1-.9 4.04l-.13.3 7.91 7.9v5.6H25.7l-4.13-4.13zM10.31 7.22a3.1 3.1 0 1 1 0 6.19 3.1 3.1 0 0 1 0-6.2zm0 2.06a1.03 1.03 0 1 0 0 2.06 1.03 1.03 0 0 0 0-2.06zM22.43 25.1l4.12 4.13h2.67v-2.67l-8.37-8.37.37-.68.16-.3c.56-1.15.9-2.42.96-3.77v-.64a9.28 9.28 0 0 0-9-9h-.55a9.28 9.28 0 0 0-9 9v.54a9.28 9.28 0 0 0 13.3 8.1l.3-.16 1.52-.8v4.62z"></path>
          </svg>
        </div>

        <div class="ps-2 sm:ps-4 lg:ps-6 ">
          <h4 class="text-sm font-medium">Communication</h4>
          <p class="text-lg font-medium"><%= property.average_communication_rating().round(1) %></p>
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false" 
            class="block h-8 w-8 fill-none stroke-current stroke-2 mt-6 overflow-visible"
          >
            <path fill="none" d="M26 3a4 4 0 0 1 4 4v14a4 4 0 0 1-4 4h-6.32L16 29.5 12.32 25H6a4 4 0 0 1-4-4V7a4 4 0 0 1 4-4z"></path>
          </svg>
        </div>

        <div class="ps-2 sm:ps-4 lg:ps-6 ">
          <h4 class="text-sm font-medium">Location</h4>
          <p class="text-lg font-medium"><%= property.average_location_rating().round(1) %></p>
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false"
            class="block h-8 w-8 fill-current mt-6"
          >
            <path d="M30.95 3.81a2 2 0 0 0-2.38-1.52l-7.58 1.69-10-2-8.42 1.87A1.99 1.99 0 0 0 1 5.8v21.95a1.96 1.96 0 0 0 .05.44 2 2 0 0 0 2.38 1.52l7.58-1.69 10 2 8.42-1.87A1.99 1.99 0 0 0 31 26.2V4.25a1.99 1.99 0 0 0-.05-.44zM12 4.22l8 1.6v21.96l-8-1.6zM3 27.75V5.8l-.22-.97.22.97 7-1.55V26.2zm26-1.55-7 1.55V5.8l7-1.55z"></path>
          </svg>
        </div>

        <div class="ps-2 sm:ps-4 lg:ps-6 ">
          <h4 class="text-sm font-medium">Value</h4>
          <p class="text-lg font-medium"><%= property.average_value_rating().round(1) %></p>
          <svg 
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false"
            class="block h-8 w-8 fill-current mt-6"
          >
            <path d="M16.17 2a3 3 0 0 1 1.98.74l.14.14 11 11a3 3 0 0 1 .14 4.1l-.14.14L18.12 29.3a3 3 0 0 1-4.1.14l-.14-.14-11-11A3 3 0 0 1 2 16.37l-.01-.2V5a3 3 0 0 1 2.82-3h11.35zm0 2H5a1 1 0 0 0-1 .88v11.29a1 1 0 0 0 .2.61l.1.1 11 11a1 1 0 0 0 1.31.08l.1-.08L27.88 16.7a1 1 0 0 0 .08-1.32l-.08-.1-11-11a1 1 0 0 0-.58-.28L16.17 4zM9 6a3 3 0 1 1 0 6 3 3 0 0 1 0-6zm0 2a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
          </svg>
        </div>
      </div>
    <%end %>
  </section>

  <!-- Review items-->
  <section aria-labelledby="reviews-items" class="border-t border-gray-200 pt-6 lg:pt-6">
    <div class="space-y-10">
      <div class="lg:grid lg:grid-cols-2 lg:gap-4 space-y-8 lg:space-y-0">
        <%# TODO: Show latest reviews first. Apply this for other models also. %>
        <% property.reviews.limit(6).each do |review| %>
          <%= render 'properties/review_item', review: review %>
        <% end %>
      </div>
      <% if property.reviews_count > 1 %>
        <button 
          type="button" 
          data-controller="reviews"
          data-action="click->reviews#toggleReviewsModal"
          class="rounded-md bg-white px-4 py-3 text-sm font-medium text-gray-900 text-lg ring-1 ring-inset ring-black hover:bg-gray-50"
        >
          Show all <%= property.reviews_count %> reviews
        </button>
      <% end %>
    </div>
  </section>
</div>

<% if property.reviews_count > 0 %>
  <%#= render 'shared/modal', modalTriggerId: "reviews", content: 'properties/reviews_modal', content_params: {property: property} %>
<% end %>